# Generated by Django 6.0.5 on 2026-06-01 23:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='براء رائد لمعارض السيارات', max_length=200)),
                ('address', models.CharField(blank=True, default='العراق', max_length=500)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('commercial_register', models.CharField(blank=True, max_length=64)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='IQD', max_length=8)),
                ('invoice_footer', models.TextField(blank=True)),
                ('contract_legal_text', models.TextField(blank=True)),
                ('print_margin_mm', models.PositiveSmallIntegerField(default=12)),
                ('paper_size', models.CharField(default='A4', max_length=16)),
                ('manager_name', models.CharField(blank=True, default='المدير العام', max_length=120)),
                ('manager_title', models.CharField(blank=True, default='إدارة المعرض', max_length=120)),
                ('show_qr', models.BooleanField(default=True)),
                ('show_barcode', models.BooleanField(default=True)),
                ('show_stamp', models.BooleanField(default=True)),
                ('show_manager_signature', models.BooleanField(default=True)),
                ('show_client_signature', models.BooleanField(default=True)),
                ('logo_data_url', models.TextField(blank=True)),
                ('stamp_data_url', models.TextField(blank=True)),
                ('signature_data_url', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ملف الشركة',
                'verbose_name_plural': 'ملف الشركة',
            },
        ),
        migrations.CreateModel(
            name='BranchPrintOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_display_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_override', to='accounts.branch')),
            ],
        ),
    ]
