# Generated by Django 6.0.5 on 2026-06-01 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_number', models.CharField(db_index=True, max_length=64)),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('plate_number', models.CharField(blank=True, max_length=32)),
                ('manufacturer', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('trim', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('exterior_color', models.CharField(blank=True, max_length=64)),
                ('interior_color', models.CharField(blank=True, max_length=64)),
                ('fuel_type', models.CharField(blank=True, default='بنزين', max_length=32)),
                ('transmission', models.CharField(blank=True, default='أوتوماتيك', max_length=32)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('minimum_sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('maintenance_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('transportation_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('available', 'متوفرة'), ('reserved', 'محجوزة'), ('sold', 'مباعة'), ('maintenance', 'صيانة'), ('transferred', 'منقولة'), ('not_ready', 'غير جاهزة')], db_index=True, default='available', max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('doc_type', models.CharField(blank=True, default='other', max_length=32)),
                ('data_url', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('data_url', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('internal_number',), name='uniq_active_internal_number'),
        ),
    ]
