# Generated by Django 6.0.5 on 2026-06-02 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_printlog'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(default='الفرع الرئيسي', max_length=120)),
                ('business_date', models.DateField(db_index=True)),
                ('opening_balance', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('expense_type', models.CharField(choices=[('general', 'عام'), ('maintenance', 'صيانة'), ('transport', 'نقل'), ('purchase', 'شراء'), ('payroll', 'رواتب'), ('marketing', 'تسويق'), ('other', 'أخرى')], db_index=True, default='general', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('branch_name', models.CharField(default='الفرع الرئيسي', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expenses', to='sales.saleinvoice')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], db_index=True, max_length=8)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('category', models.CharField(default='حركة نقدية', max_length=80)),
                ('reference_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='sales.saleinvoice')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='vehicles.vehicle')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.dailycashregister')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='accounting.expense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailycashregister',
            constraint=models.UniqueConstraint(fields=('branch_name', 'business_date'), name='uniq_cash_register_branch_date'),
        ),
    ]
