import {
  Activity,
  BadgeDollarSign,
  Bell,
  Building2,
  Car,
  CheckCircle2,
  ClipboardCheck,
  DatabaseBackup,
  FileDown,
  FileText,
  Gauge,
  KeyRound,
  MessageCircle,
  PackageCheck,
  Printer,
  Receipt,
  ShieldCheck,
  Sparkles,
  UserRoundPlus,
  Users,
  Wrench
} from "lucide-react";
import type { ModuleKey } from "@/lib/domain";

export const moduleIcons: Record<ModuleKey, React.ReactNode> = {
  dashboard: <Gauge className="h-4 w-4" />,
  cars: <Car className="h-4 w-4" />,
  customers: <Users className="h-4 w-4" />,
  leads: <UserRoundPlus className="h-4 w-4" />,
  sales: <Receipt className="h-4 w-4" />,
  installments: <BadgeDollarSign className="h-4 w-4" />,
  purchases: <PackageCheck className="h-4 w-4" />,
  inventory: <ClipboardCheck className="h-4 w-4" />,
  accounting: <FileText className="h-4 w-4" />,
  employees: <Users className="h-4 w-4" />,
  branches: <Building2 className="h-4 w-4" />,
  reservations: <CheckCircle2 className="h-4 w-4" />,
  "test-drives": <Gauge className="h-4 w-4" />,
  maintenance: <Wrench className="h-4 w-4" />,
  insurance: <ShieldCheck className="h-4 w-4" />,
  offers: <Sparkles className="h-4 w-4" />,
  whatsapp: <MessageCircle className="h-4 w-4" />,
  reports: <FileDown className="h-4 w-4" />,
  notifications: <Bell className="h-4 w-4" />,
  permissions: <KeyRound className="h-4 w-4" />,
  printing: <Printer className="h-4 w-4" />,
  "backup-sync": <DatabaseBackup className="h-4 w-4" />,
  "system-health": <Activity className="h-4 w-4" />,
  settings: <ShieldCheck className="h-4 w-4" />
};
