# Generated by Django 6.0.5 on 2026-06-02 00:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_printlog'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('installment_count', models.PositiveSmallIntegerField(default=1)),
                ('branch_name', models.CharField(default='الفرع الرئيسي', max_length=120)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_contracts_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_contracts', to='customers.customer')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_contracts', to='sales.saleinvoice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_contracts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'مستحق'), ('paid', 'مدفوع'), ('overdue', 'متأخر')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='installments.installmentcontract')),
            ],
            options={
                'ordering': ['contract', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt_reference', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='sales.saleinvoice')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='installments.installmentscheduleentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='installmentscheduleentry',
            constraint=models.UniqueConstraint(fields=('contract', 'sequence'), name='uniq_schedule_sequence_per_contract'),
        ),
    ]
