# Generated by Django 6.0.5 on 2026-06-02 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('WhatsApp', 'واتساب'), ('Facebook', 'فيسبوك'), ('Instagram', 'إنستغرام'), ('Walk-In', 'زيارة مباشرة'), ('Phone Call', 'اتصال هاتفي')], default='WhatsApp', max_length=32)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('interested', 'مهتم'), ('contact', 'تواصل'), ('reserved', 'حجز'), ('purchased', 'اشترى'), ('cancelled', 'ملغي')], db_index=True, default='interested', max_length=20)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
