# Generated by Django 6.0.5 on 2026-06-02 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=120)),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('converted', 'تحوّل لبيع')], db_index=True, default='active', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('payment_type', models.CharField(choices=[('cash', 'نقد'), ('bank-transfer', 'تحويل بنكي'), ('installment', 'تقسيط'), ('mixed', 'مختلط')], default='cash', max_length=20)),
                ('total', models.DecimalField(decimal_places=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'صادرة'), ('revised', 'معدّلة'), ('cancelled', 'ملغاة')], db_index=True, default='issued', max_length=20)),
                ('discount_requires_approval', models.BooleanField(default=False)),
                ('discount_approved', models.BooleanField(default=False)),
                ('sold_with_reserved_override', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='customers.customer')),
                ('discount_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_approvals', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False), ('status', 'issued')), fields=('vehicle',), name='uniq_active_sale_per_vehicle')],
            },
        ),
    ]
