# Generated by Django 6.0.5 on 2026-06-02 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'فاتورة'), ('contract', 'عقد'), ('receipt', 'إيصال'), ('report', 'تقرير')], db_index=True, max_length=20)),
                ('document_number', models.CharField(db_index=True, max_length=64)),
                ('branch_name', models.CharField(default='الفرع الرئيسي', max_length=120)),
                ('print_count', models.PositiveIntegerField(default=1)),
                ('printed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_logs', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_logs', to='sales.saleinvoice')),
            ],
            options={
                'ordering': ['-printed_at'],
                'indexes': [models.Index(fields=['document_type', 'document_number'], name='sales_print_documen_d278b5_idx')],
            },
        ),
    ]
