# Generated by Django 6.0.5 on 2026-06-02 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('error', 'خطأ'), ('critical', 'حرج')], default='error', max_length=16)),
                ('source', models.CharField(db_index=True, max_length=120)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, max_length=512)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('manual', 'يدوي'), ('auto', 'تلقائي')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('success', 'نجاح'), ('failed', 'فشل')], db_index=True, default='pending', max_length=16)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('entity_counts', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('partial', 'جزئي'), ('failed', 'فشل')], max_length=16)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('remaining_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
